### ISSUE TITLE
About other attributes.

### ISSUE THREAD

**Issue by LynnHo** [zhangqianhui/Residual_Image_Learning_GAN#3]
@zhangqianhui Thanks for the code!!! It's really helpful!!! I saw that you post the results of changing gender. What about other attributes? Have you conducted experiments on other attributes?

**Comment by zhangqianhui** [comment]
@LynnHo 
(1) this code doesn't contain the dual loss, you can add it as the classification problem.
(2)For more attributes, you just need change the id of attibute in utils.py.
now the id of gender is 20. You can change this value for other attibutes.
`flag = line.split('1 ', 41)[20] # get the label for gender`
