### ISSUE TITLE
What's the GAN loss function?

### ISSUE THREAD

**Issue by MingtaoGuo** [zhangqianhui/Residual_Image_Learning_GAN#4]
In this paper,How can i understand the formula(6,7)，the discriminator is a classification and it have 3 categories.

**Comment by zhangqianhui** [comment]
You should firstly read this paper https://arxiv.org/abs/1606.03498

And the three categories can be divided into 2 categories classification
and gan loss.


2018-05-01 20:09 GMT+08:00 MarTinGuo <notifications@github.com>:

**Comment by MingtaoGuo** [comment]
Thank you for your constructive opinion，can i ask you that how long do you train the networks? My result is really not good in test data for glasses removal.

**Comment by zhangqianhui** [comment]
Can you show some results of your experiments?
